# Generated by Django 4.2 on 2023-04-10 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_home', '0006_alter_todo_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='decription',
            new_name='description',
        ),
    ]
